version: "3.8"

services:
  shortener:
    image: maksymbondarenko00/shortener
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/shortener
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Loxy1517.
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Loxy1517.
      MYSQL_DATABASE: shortener
    ports:
      - "3306:3306"

  nginx:
    image: public.ecr.aws/nginx/nginx:1.27.1-alpine3.20-perl
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=shortener
      - NGINX_PORT=8080
    depends_on:
      - shortener